name: .NET Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 15

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build and test
        run: |
          dotnet restore TestUtilitiesDemo/TestUtilitiesDemo.csproj
          dotnet restore TestUtilitiesDemo.Tests/TestUtilitiesDemo.Tests.csproj
          dotnet build --configuration Release TestUtilitiesDemo/TestUtilitiesDemo.csproj
          dotnet build --configuration Release TestUtilitiesDemo.Tests/TestUtilitiesDemo.Tests.csproj
          dotnet test TestUtilitiesDemo.Tests/TestUtilitiesDemo.Tests.csproj